version: '3'
services:
  pytha-redis01:
    image: redis:5.0.4-alpine
    container_name: pytha-redis01
    hostname: pytha-redis01
    restart: always
    ports:
      - "16379:6379"
    networks:
      - dev
    volumes:
      - /data:/data
      - /root/compose/pytha/conf/redis.conf:/usr/local/etc/redis/redis.conf

networks:
  dev:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.0.0/16

